version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/var/jenkins_home/workspace
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: bash -c "
      curl -fsSL https://get.docker.com | sh &&
      curl -L 'https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64' -o /usr/local/bin/docker-compose &&
      chmod +x /usr/local/bin/docker-compose &&
      /usr/local/bin/jenkins.sh"
    networks:
      - app-network

volumes:
  jenkins_home:

networks:
  app-network:
    driver: bridge
