apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: astrofarmers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: meryem1911/astro-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_API_URL
              value: http://backend:8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: astrofarmers
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
